// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cn/com/sparkle/raptor/test/model/protocolbuffer/Person.proto

package cn.com.sparkle.raptor.test.model.protocolbuffer;

public final class PersonMessage {
  private PersonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddressBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protocolbuffer.Person person = 1;
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    java.util.List<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person> 
        getPersonList();
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person getPerson(int index);
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    java.util.List<? extends cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocolbuffer.AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage
      implements AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.class, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    // repeated .protocolbuffer.Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person> person_;
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    public java.util.List<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    public java.util.List<? extends cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .protocolbuffer.Person person = 1;</code>
     */
    public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocolbuffer.AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.class, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.Builder.class);
      }

      // Construct using cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_AddressBook_descriptor;
      }

      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook getDefaultInstanceForType() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.getDefaultInstance();
      }

      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook build() {
        cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook buildPartial() {
        cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook result = new cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook) {
          return mergeFrom((cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook other) {
        if (other == cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protocolbuffer.Person person = 1;
      private java.util.List<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public java.util.List<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder addPerson(cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder addPerson(
          cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public java.util.List<? extends cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .protocolbuffer.Person person = 1;</code>
       */
      public java.util.List<cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocolbuffer.AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocolbuffer.AddressBook)
  }

  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code protocolbuffer.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.class, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocolbuffer.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.class, cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.Builder.class);
      }

      // Construct using cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.internal_static_protocolbuffer_Person_descriptor;
      }

      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person getDefaultInstanceForType() {
        return cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.getDefaultInstance();
      }

      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person build() {
        cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person buildPartial() {
        cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person result = new cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person) {
          return mergeFrom((cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person other) {
        if (other == cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.com.sparkle.raptor.test.model.protocolbuffer.PersonMessage.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocolbuffer.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocolbuffer.Person)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolbuffer_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocolbuffer_AddressBook_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolbuffer_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocolbuffer_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<cn/com/sparkle/raptor/test/model/proto" +
      "colbuffer/Person.proto\022\016protocolbuffer\"5" +
      "\n\013AddressBook\022&\n\006person\030\001 \003(\0132\026.protocol" +
      "buffer.Person\"1\n\006Person\022\n\n\002id\030\001 \002(\005\022\014\n\004n" +
      "ame\030\002 \002(\t\022\r\n\005email\030\003 \001(\tB@\n/cn.com.spark" +
      "le.raptor.test.model.protocolbufferB\rPer" +
      "sonMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocolbuffer_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocolbuffer_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocolbuffer_AddressBook_descriptor,
              new java.lang.String[] { "Person", });
          internal_static_protocolbuffer_Person_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocolbuffer_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocolbuffer_Person_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
