// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package cn.com.sparkle.paxos.stablestorage.model;

public final class StoreModel {
	private StoreModel() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface ValueOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required int32 type = 1;
		/**
		 * <code>required int32 type = 1;</code>
		 */
		boolean hasType();

		/**
		 * <code>required int32 type = 1;</code>
		 */
		int getType();

		// repeated bytes values = 2;
		/**
		 * <code>repeated bytes values = 2;</code>
		 */
		java.util.List<com.google.protobuf.ByteString> getValuesList();

		/**
		 * <code>repeated bytes values = 2;</code>
		 */
		int getValuesCount();

		/**
		 * <code>repeated bytes values = 2;</code>
		 */
		com.google.protobuf.ByteString getValues(int index);
	}

	/**
	 * Protobuf type {@code protocolbuffer.Value}
	 */
	public static final class Value extends com.google.protobuf.GeneratedMessage implements ValueOrBuilder {
		// Use Value.newBuilder() to construct.
		private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Value(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final Value defaultInstance;

		public static Value getDefaultInstance() {
			return defaultInstance;
		}

		public Value getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Value(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						type_ = input.readInt32();
						break;
					}
					case 18: {
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
							values_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
							mutable_bitField0_ |= 0x00000002;
						}
						values_.add(input.readBytes());
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					values_ = java.util.Collections.unmodifiableList(values_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Value_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Value_fieldAccessorTable.ensureFieldAccessorsInitialized(
					cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.class, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder.class);
		}

		public static com.google.protobuf.Parser<Value> PARSER = new com.google.protobuf.AbstractParser<Value>() {
			public Value parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Value(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<Value> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required int32 type = 1;
		public static final int TYPE_FIELD_NUMBER = 1;
		private int type_;

		/**
		 * <code>required int32 type = 1;</code>
		 */
		public boolean hasType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 type = 1;</code>
		 */
		public int getType() {
			return type_;
		}

		// repeated bytes values = 2;
		public static final int VALUES_FIELD_NUMBER = 2;
		private java.util.List<com.google.protobuf.ByteString> values_;

		/**
		 * <code>repeated bytes values = 2;</code>
		 */
		public java.util.List<com.google.protobuf.ByteString> getValuesList() {
			return values_;
		}

		/**
		 * <code>repeated bytes values = 2;</code>
		 */
		public int getValuesCount() {
			return values_.size();
		}

		/**
		 * <code>repeated bytes values = 2;</code>
		 */
		public com.google.protobuf.ByteString getValues(int index) {
			return values_.get(index);
		}

		private void initFields() {
			type_ = 0;
			values_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, type_);
			}
			for (int i = 0; i < values_.size(); i++) {
				output.writeBytes(2, values_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, type_);
			}
			{
				int dataSize = 0;
				for (int i = 0; i < values_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(values_.get(i));
				}
				size += dataSize;
				size += 1 * getValuesList().size();
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code protocolbuffer.Value}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Value_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Value_fieldAccessorTable
						.ensureFieldAccessorsInitialized(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.class,
								cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder.class);
			}

			// Construct using cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				type_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				values_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Value_descriptor;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getDefaultInstanceForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value build() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value buildPartial() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value result = new cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.type_ = type_;
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					values_ = java.util.Collections.unmodifiableList(values_);
					bitField0_ = (bitField0_ & ~0x00000002);
				}
				result.values_ = values_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value) {
					return mergeFrom((cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value other) {
				if (other == cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance())
					return this;
				if (other.hasType()) {
					setType(other.getType());
				}
				if (!other.values_.isEmpty()) {
					if (values_.isEmpty()) {
						values_ = other.values_;
						bitField0_ = (bitField0_ & ~0x00000002);
					} else {
						ensureValuesIsMutable();
						values_.addAll(other.values_);
					}
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasType()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required int32 type = 1;
			private int type_;

			/**
			 * <code>required int32 type = 1;</code>
			 */
			public boolean hasType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 type = 1;</code>
			 */
			public int getType() {
				return type_;
			}

			/**
			 * <code>required int32 type = 1;</code>
			 */
			public Builder setType(int value) {
				bitField0_ |= 0x00000001;
				type_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 type = 1;</code>
			 */
			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				type_ = 0;
				onChanged();
				return this;
			}

			// repeated bytes values = 2;
			private java.util.List<com.google.protobuf.ByteString> values_ = java.util.Collections.emptyList();

			private void ensureValuesIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					values_ = new java.util.ArrayList<com.google.protobuf.ByteString>(values_);
					bitField0_ |= 0x00000002;
				}
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public java.util.List<com.google.protobuf.ByteString> getValuesList() {
				return java.util.Collections.unmodifiableList(values_);
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public int getValuesCount() {
				return values_.size();
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public com.google.protobuf.ByteString getValues(int index) {
				return values_.get(index);
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public Builder setValues(int index, com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureValuesIsMutable();
				values_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public Builder addValues(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureValuesIsMutable();
				values_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public Builder addAllValues(java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
				ensureValuesIsMutable();
				super.addAll(values, values_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated bytes values = 2;</code>
			 */
			public Builder clearValues() {
				values_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:protocolbuffer.Value)
		}

		static {
			defaultInstance = new Value(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:protocolbuffer.Value)
	}

	public interface IdOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required int64 increaseId = 1;
		/**
		 * <code>required int64 increaseId = 1;</code>
		 */
		boolean hasIncreaseId();

		/**
		 * <code>required int64 increaseId = 1;</code>
		 */
		long getIncreaseId();

		// required string address = 2;
		/**
		 * <code>required string address = 2;</code>
		 */
		boolean hasAddress();

		/**
		 * <code>required string address = 2;</code>
		 */
		java.lang.String getAddress();

		/**
		 * <code>required string address = 2;</code>
		 */
		com.google.protobuf.ByteString getAddressBytes();
	}

	/**
	 * Protobuf type {@code protocolbuffer.Id}
	 */
	public static final class Id extends com.google.protobuf.GeneratedMessage implements IdOrBuilder {
		// Use Id.newBuilder() to construct.
		private Id(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Id(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final Id defaultInstance;

		public static Id getDefaultInstance() {
			return defaultInstance;
		}

		public Id getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Id(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						increaseId_ = input.readInt64();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						address_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Id_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Id_fieldAccessorTable.ensureFieldAccessorsInitialized(
					cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.class, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder.class);
		}

		public static com.google.protobuf.Parser<Id> PARSER = new com.google.protobuf.AbstractParser<Id>() {
			public Id parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Id(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<Id> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required int64 increaseId = 1;
		public static final int INCREASEID_FIELD_NUMBER = 1;
		private long increaseId_;

		/**
		 * <code>required int64 increaseId = 1;</code>
		 */
		public boolean hasIncreaseId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int64 increaseId = 1;</code>
		 */
		public long getIncreaseId() {
			return increaseId_;
		}

		// required string address = 2;
		public static final int ADDRESS_FIELD_NUMBER = 2;
		private java.lang.Object address_;

		/**
		 * <code>required string address = 2;</code>
		 */
		public boolean hasAddress() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required string address = 2;</code>
		 */
		public java.lang.String getAddress() {
			java.lang.Object ref = address_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					address_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string address = 2;</code>
		 */
		public com.google.protobuf.ByteString getAddressBytes() {
			java.lang.Object ref = address_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				address_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			increaseId_ = 0L;
			address_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasIncreaseId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasAddress()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, increaseId_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getAddressBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, increaseId_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getAddressBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code protocolbuffer.Id}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Id_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Id_fieldAccessorTable
						.ensureFieldAccessorsInitialized(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.class,
								cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder.class);
			}

			// Construct using cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				increaseId_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				address_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_Id_descriptor;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getDefaultInstanceForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id build() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id buildPartial() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id result = new cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.increaseId_ = increaseId_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.address_ = address_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id) {
					return mergeFrom((cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id other) {
				if (other == cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance())
					return this;
				if (other.hasIncreaseId()) {
					setIncreaseId(other.getIncreaseId());
				}
				if (other.hasAddress()) {
					bitField0_ |= 0x00000002;
					address_ = other.address_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasIncreaseId()) {

					return false;
				}
				if (!hasAddress()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required int64 increaseId = 1;
			private long increaseId_;

			/**
			 * <code>required int64 increaseId = 1;</code>
			 */
			public boolean hasIncreaseId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int64 increaseId = 1;</code>
			 */
			public long getIncreaseId() {
				return increaseId_;
			}

			/**
			 * <code>required int64 increaseId = 1;</code>
			 */
			public Builder setIncreaseId(long value) {
				bitField0_ |= 0x00000001;
				increaseId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int64 increaseId = 1;</code>
			 */
			public Builder clearIncreaseId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				increaseId_ = 0L;
				onChanged();
				return this;
			}

			// required string address = 2;
			private java.lang.Object address_ = "";

			/**
			 * <code>required string address = 2;</code>
			 */
			public boolean hasAddress() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string address = 2;</code>
			 */
			public java.lang.String getAddress() {
				java.lang.Object ref = address_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					address_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string address = 2;</code>
			 */
			public com.google.protobuf.ByteString getAddressBytes() {
				java.lang.Object ref = address_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					address_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string address = 2;</code>
			 */
			public Builder setAddress(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				address_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string address = 2;</code>
			 */
			public Builder clearAddress() {
				bitField0_ = (bitField0_ & ~0x00000002);
				address_ = getDefaultInstance().getAddress();
				onChanged();
				return this;
			}

			/**
			 * <code>required string address = 2;</code>
			 */
			public Builder setAddressBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				address_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:protocolbuffer.Id)
		}

		static {
			defaultInstance = new Id(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:protocolbuffer.Id)
	}

	public interface InstanceVoteRecordOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required .protocolbuffer.Id highestJoinNum = 2;
		/**
		 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
		 */
		boolean hasHighestJoinNum();

		/**
		 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestJoinNum();

		/**
		 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestJoinNumOrBuilder();

		// optional .protocolbuffer.Id highestVotedNum = 3;
		/**
		 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
		 */
		boolean hasHighestVotedNum();

		/**
		 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestVotedNum();

		/**
		 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestVotedNumOrBuilder();

		// optional .protocolbuffer.Value highestValue = 4;
		/**
		 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
		 */
		boolean hasHighestValue();

		/**
		 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getHighestValue();

		/**
		 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder getHighestValueOrBuilder();
	}

	/**
	 * Protobuf type {@code protocolbuffer.InstanceVoteRecord}
	 */
	public static final class InstanceVoteRecord extends com.google.protobuf.GeneratedMessage implements InstanceVoteRecordOrBuilder {
		// Use InstanceVoteRecord.newBuilder() to construct.
		private InstanceVoteRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private InstanceVoteRecord(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final InstanceVoteRecord defaultInstance;

		public static InstanceVoteRecord getDefaultInstance() {
			return defaultInstance;
		}

		public InstanceVoteRecord getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private InstanceVoteRecord(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 18: {
						cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder subBuilder = null;
						if (((bitField0_ & 0x00000001) == 0x00000001)) {
							subBuilder = highestJoinNum_.toBuilder();
						}
						highestJoinNum_ = input.readMessage(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.PARSER, extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(highestJoinNum_);
							highestJoinNum_ = subBuilder.buildPartial();
						}
						bitField0_ |= 0x00000001;
						break;
					}
					case 26: {
						cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder subBuilder = null;
						if (((bitField0_ & 0x00000002) == 0x00000002)) {
							subBuilder = highestVotedNum_.toBuilder();
						}
						highestVotedNum_ = input.readMessage(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.PARSER, extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(highestVotedNum_);
							highestVotedNum_ = subBuilder.buildPartial();
						}
						bitField0_ |= 0x00000002;
						break;
					}
					case 34: {
						cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder subBuilder = null;
						if (((bitField0_ & 0x00000004) == 0x00000004)) {
							subBuilder = highestValue_.toBuilder();
						}
						highestValue_ = input.readMessage(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.PARSER, extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(highestValue_);
							highestValue_ = subBuilder.buildPartial();
						}
						bitField0_ |= 0x00000004;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_InstanceVoteRecord_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_InstanceVoteRecord_fieldAccessorTable
					.ensureFieldAccessorsInitialized(cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.class,
							cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.Builder.class);
		}

		public static com.google.protobuf.Parser<InstanceVoteRecord> PARSER = new com.google.protobuf.AbstractParser<InstanceVoteRecord>() {
			public InstanceVoteRecord parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new InstanceVoteRecord(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<InstanceVoteRecord> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required .protocolbuffer.Id highestJoinNum = 2;
		public static final int HIGHESTJOINNUM_FIELD_NUMBER = 2;
		private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id highestJoinNum_;

		/**
		 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
		 */
		public boolean hasHighestJoinNum() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestJoinNum() {
			return highestJoinNum_;
		}

		/**
		 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestJoinNumOrBuilder() {
			return highestJoinNum_;
		}

		// optional .protocolbuffer.Id highestVotedNum = 3;
		public static final int HIGHESTVOTEDNUM_FIELD_NUMBER = 3;
		private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id highestVotedNum_;

		/**
		 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
		 */
		public boolean hasHighestVotedNum() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestVotedNum() {
			return highestVotedNum_;
		}

		/**
		 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestVotedNumOrBuilder() {
			return highestVotedNum_;
		}

		// optional .protocolbuffer.Value highestValue = 4;
		public static final int HIGHESTVALUE_FIELD_NUMBER = 4;
		private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value highestValue_;

		/**
		 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
		 */
		public boolean hasHighestValue() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getHighestValue() {
			return highestValue_;
		}

		/**
		 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder getHighestValueOrBuilder() {
			return highestValue_;
		}

		private void initFields() {
			highestJoinNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
			highestVotedNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
			highestValue_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasHighestJoinNum()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!getHighestJoinNum().isInitialized()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (hasHighestVotedNum()) {
				if (!getHighestVotedNum().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			if (hasHighestValue()) {
				if (!getHighestValue().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeMessage(2, highestJoinNum_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeMessage(3, highestVotedNum_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeMessage(4, highestValue_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, highestJoinNum_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, highestVotedNum_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, highestValue_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code protocolbuffer.InstanceVoteRecord}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecordOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_InstanceVoteRecord_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_InstanceVoteRecord_fieldAccessorTable
						.ensureFieldAccessorsInitialized(cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.class,
								cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.Builder.class);
			}

			// Construct using cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getHighestJoinNumFieldBuilder();
					getHighestVotedNumFieldBuilder();
					getHighestValueFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (highestJoinNumBuilder_ == null) {
					highestJoinNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
				} else {
					highestJoinNumBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				if (highestVotedNumBuilder_ == null) {
					highestVotedNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
				} else {
					highestVotedNumBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				if (highestValueBuilder_ == null) {
					highestValue_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
				} else {
					highestValueBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_InstanceVoteRecord_descriptor;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord getDefaultInstanceForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.getDefaultInstance();
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord build() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord buildPartial() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord result = new cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				if (highestJoinNumBuilder_ == null) {
					result.highestJoinNum_ = highestJoinNum_;
				} else {
					result.highestJoinNum_ = highestJoinNumBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				if (highestVotedNumBuilder_ == null) {
					result.highestVotedNum_ = highestVotedNum_;
				} else {
					result.highestVotedNum_ = highestVotedNumBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				if (highestValueBuilder_ == null) {
					result.highestValue_ = highestValue_;
				} else {
					result.highestValue_ = highestValueBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord) {
					return mergeFrom((cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord other) {
				if (other == cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord.getDefaultInstance())
					return this;
				if (other.hasHighestJoinNum()) {
					mergeHighestJoinNum(other.getHighestJoinNum());
				}
				if (other.hasHighestVotedNum()) {
					mergeHighestVotedNum(other.getHighestVotedNum());
				}
				if (other.hasHighestValue()) {
					mergeHighestValue(other.getHighestValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasHighestJoinNum()) {

					return false;
				}
				if (!getHighestJoinNum().isInitialized()) {

					return false;
				}
				if (hasHighestVotedNum()) {
					if (!getHighestVotedNum().isInitialized()) {

						return false;
					}
				}
				if (hasHighestValue()) {
					if (!getHighestValue().isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (cn.com.sparkle.paxos.stablestorage.model.StoreModel.InstanceVoteRecord) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required .protocolbuffer.Id highestJoinNum = 2;
			private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id highestJoinNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder> highestJoinNumBuilder_;

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public boolean hasHighestJoinNum() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestJoinNum() {
				if (highestJoinNumBuilder_ == null) {
					return highestJoinNum_;
				} else {
					return highestJoinNumBuilder_.getMessage();
				}
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public Builder setHighestJoinNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id value) {
				if (highestJoinNumBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					highestJoinNum_ = value;
					onChanged();
				} else {
					highestJoinNumBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000001;
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public Builder setHighestJoinNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder builderForValue) {
				if (highestJoinNumBuilder_ == null) {
					highestJoinNum_ = builderForValue.build();
					onChanged();
				} else {
					highestJoinNumBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000001;
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public Builder mergeHighestJoinNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id value) {
				if (highestJoinNumBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)
							&& highestJoinNum_ != cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance()) {
						highestJoinNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.newBuilder(highestJoinNum_).mergeFrom(value).buildPartial();
					} else {
						highestJoinNum_ = value;
					}
					onChanged();
				} else {
					highestJoinNumBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000001;
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public Builder clearHighestJoinNum() {
				if (highestJoinNumBuilder_ == null) {
					highestJoinNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
					onChanged();
				} else {
					highestJoinNumBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder getHighestJoinNumBuilder() {
				bitField0_ |= 0x00000001;
				onChanged();
				return getHighestJoinNumFieldBuilder().getBuilder();
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestJoinNumOrBuilder() {
				if (highestJoinNumBuilder_ != null) {
					return highestJoinNumBuilder_.getMessageOrBuilder();
				} else {
					return highestJoinNum_;
				}
			}

			/**
			 * <code>required .protocolbuffer.Id highestJoinNum = 2;</code>
			 */
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder> getHighestJoinNumFieldBuilder() {
				if (highestJoinNumBuilder_ == null) {
					highestJoinNumBuilder_ = new com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder>(
							highestJoinNum_, getParentForChildren(), isClean());
					highestJoinNum_ = null;
				}
				return highestJoinNumBuilder_;
			}

			// optional .protocolbuffer.Id highestVotedNum = 3;
			private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id highestVotedNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder> highestVotedNumBuilder_;

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public boolean hasHighestVotedNum() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestVotedNum() {
				if (highestVotedNumBuilder_ == null) {
					return highestVotedNum_;
				} else {
					return highestVotedNumBuilder_.getMessage();
				}
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public Builder setHighestVotedNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id value) {
				if (highestVotedNumBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					highestVotedNum_ = value;
					onChanged();
				} else {
					highestVotedNumBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public Builder setHighestVotedNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder builderForValue) {
				if (highestVotedNumBuilder_ == null) {
					highestVotedNum_ = builderForValue.build();
					onChanged();
				} else {
					highestVotedNumBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public Builder mergeHighestVotedNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id value) {
				if (highestVotedNumBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)
							&& highestVotedNum_ != cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance()) {
						highestVotedNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.newBuilder(highestVotedNum_).mergeFrom(value).buildPartial();
					} else {
						highestVotedNum_ = value;
					}
					onChanged();
				} else {
					highestVotedNumBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public Builder clearHighestVotedNum() {
				if (highestVotedNumBuilder_ == null) {
					highestVotedNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
					onChanged();
				} else {
					highestVotedNumBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder getHighestVotedNumBuilder() {
				bitField0_ |= 0x00000002;
				onChanged();
				return getHighestVotedNumFieldBuilder().getBuilder();
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestVotedNumOrBuilder() {
				if (highestVotedNumBuilder_ != null) {
					return highestVotedNumBuilder_.getMessageOrBuilder();
				} else {
					return highestVotedNum_;
				}
			}

			/**
			 * <code>optional .protocolbuffer.Id highestVotedNum = 3;</code>
			 */
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder> getHighestVotedNumFieldBuilder() {
				if (highestVotedNumBuilder_ == null) {
					highestVotedNumBuilder_ = new com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder>(
							highestVotedNum_, getParentForChildren(), isClean());
					highestVotedNum_ = null;
				}
				return highestVotedNumBuilder_;
			}

			// optional .protocolbuffer.Value highestValue = 4;
			private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value highestValue_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder> highestValueBuilder_;

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public boolean hasHighestValue() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getHighestValue() {
				if (highestValueBuilder_ == null) {
					return highestValue_;
				} else {
					return highestValueBuilder_.getMessage();
				}
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public Builder setHighestValue(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value value) {
				if (highestValueBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					highestValue_ = value;
					onChanged();
				} else {
					highestValueBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public Builder setHighestValue(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder builderForValue) {
				if (highestValueBuilder_ == null) {
					highestValue_ = builderForValue.build();
					onChanged();
				} else {
					highestValueBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public Builder mergeHighestValue(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value value) {
				if (highestValueBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004)
							&& highestValue_ != cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance()) {
						highestValue_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.newBuilder(highestValue_).mergeFrom(value).buildPartial();
					} else {
						highestValue_ = value;
					}
					onChanged();
				} else {
					highestValueBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000004;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public Builder clearHighestValue() {
				if (highestValueBuilder_ == null) {
					highestValue_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
					onChanged();
				} else {
					highestValueBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder getHighestValueBuilder() {
				bitField0_ |= 0x00000004;
				onChanged();
				return getHighestValueFieldBuilder().getBuilder();
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder getHighestValueOrBuilder() {
				if (highestValueBuilder_ != null) {
					return highestValueBuilder_.getMessageOrBuilder();
				} else {
					return highestValue_;
				}
			}

			/**
			 * <code>optional .protocolbuffer.Value highestValue = 4;</code>
			 */
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder> getHighestValueFieldBuilder() {
				if (highestValueBuilder_ == null) {
					highestValueBuilder_ = new com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder>(
							highestValue_, getParentForChildren(), isClean());
					highestValue_ = null;
				}
				return highestValueBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:protocolbuffer.InstanceVoteRecord)
		}

		static {
			defaultInstance = new InstanceVoteRecord(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:protocolbuffer.InstanceVoteRecord)
	}

	public interface SuccessfulRecordOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required .protocolbuffer.Id highestVoteNum = 1;
		/**
		 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
		 */
		boolean hasHighestVoteNum();

		/**
		 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestVoteNum();

		/**
		 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestVoteNumOrBuilder();

		// optional .protocolbuffer.Value v = 2;
		/**
		 * <code>optional .protocolbuffer.Value v = 2;</code>
		 */
		boolean hasV();

		/**
		 * <code>optional .protocolbuffer.Value v = 2;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getV();

		/**
		 * <code>optional .protocolbuffer.Value v = 2;</code>
		 */
		cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder getVOrBuilder();
	}

	/**
	 * Protobuf type {@code protocolbuffer.SuccessfulRecord}
	 */
	public static final class SuccessfulRecord extends com.google.protobuf.GeneratedMessage implements SuccessfulRecordOrBuilder {
		// Use SuccessfulRecord.newBuilder() to construct.
		private SuccessfulRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private SuccessfulRecord(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final SuccessfulRecord defaultInstance;

		public static SuccessfulRecord getDefaultInstance() {
			return defaultInstance;
		}

		public SuccessfulRecord getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private SuccessfulRecord(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder subBuilder = null;
						if (((bitField0_ & 0x00000001) == 0x00000001)) {
							subBuilder = highestVoteNum_.toBuilder();
						}
						highestVoteNum_ = input.readMessage(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.PARSER, extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(highestVoteNum_);
							highestVoteNum_ = subBuilder.buildPartial();
						}
						bitField0_ |= 0x00000001;
						break;
					}
					case 18: {
						cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder subBuilder = null;
						if (((bitField0_ & 0x00000002) == 0x00000002)) {
							subBuilder = v_.toBuilder();
						}
						v_ = input.readMessage(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.PARSER, extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(v_);
							v_ = subBuilder.buildPartial();
						}
						bitField0_ |= 0x00000002;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_SuccessfulRecord_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_SuccessfulRecord_fieldAccessorTable
					.ensureFieldAccessorsInitialized(cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.class,
							cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.Builder.class);
		}

		public static com.google.protobuf.Parser<SuccessfulRecord> PARSER = new com.google.protobuf.AbstractParser<SuccessfulRecord>() {
			public SuccessfulRecord parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new SuccessfulRecord(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<SuccessfulRecord> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required .protocolbuffer.Id highestVoteNum = 1;
		public static final int HIGHESTVOTENUM_FIELD_NUMBER = 1;
		private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id highestVoteNum_;

		/**
		 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
		 */
		public boolean hasHighestVoteNum() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestVoteNum() {
			return highestVoteNum_;
		}

		/**
		 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestVoteNumOrBuilder() {
			return highestVoteNum_;
		}

		// optional .protocolbuffer.Value v = 2;
		public static final int V_FIELD_NUMBER = 2;
		private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value v_;

		/**
		 * <code>optional .protocolbuffer.Value v = 2;</code>
		 */
		public boolean hasV() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional .protocolbuffer.Value v = 2;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getV() {
			return v_;
		}

		/**
		 * <code>optional .protocolbuffer.Value v = 2;</code>
		 */
		public cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder getVOrBuilder() {
			return v_;
		}

		private void initFields() {
			highestVoteNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
			v_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasHighestVoteNum()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!getHighestVoteNum().isInitialized()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (hasV()) {
				if (!getV().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeMessage(1, highestVoteNum_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeMessage(2, v_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, highestVoteNum_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, v_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code protocolbuffer.SuccessfulRecord}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecordOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_SuccessfulRecord_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_SuccessfulRecord_fieldAccessorTable
						.ensureFieldAccessorsInitialized(cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.class,
								cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.Builder.class);
			}

			// Construct using cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getHighestVoteNumFieldBuilder();
					getVFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (highestVoteNumBuilder_ == null) {
					highestVoteNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
				} else {
					highestVoteNumBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				if (vBuilder_ == null) {
					v_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
				} else {
					vBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.internal_static_protocolbuffer_SuccessfulRecord_descriptor;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord getDefaultInstanceForType() {
				return cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.getDefaultInstance();
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord build() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord buildPartial() {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord result = new cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				if (highestVoteNumBuilder_ == null) {
					result.highestVoteNum_ = highestVoteNum_;
				} else {
					result.highestVoteNum_ = highestVoteNumBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				if (vBuilder_ == null) {
					result.v_ = v_;
				} else {
					result.v_ = vBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord) {
					return mergeFrom((cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord other) {
				if (other == cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord.getDefaultInstance())
					return this;
				if (other.hasHighestVoteNum()) {
					mergeHighestVoteNum(other.getHighestVoteNum());
				}
				if (other.hasV()) {
					mergeV(other.getV());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasHighestVoteNum()) {

					return false;
				}
				if (!getHighestVoteNum().isInitialized()) {

					return false;
				}
				if (hasV()) {
					if (!getV().isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (cn.com.sparkle.paxos.stablestorage.model.StoreModel.SuccessfulRecord) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required .protocolbuffer.Id highestVoteNum = 1;
			private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id highestVoteNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder> highestVoteNumBuilder_;

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public boolean hasHighestVoteNum() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id getHighestVoteNum() {
				if (highestVoteNumBuilder_ == null) {
					return highestVoteNum_;
				} else {
					return highestVoteNumBuilder_.getMessage();
				}
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public Builder setHighestVoteNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id value) {
				if (highestVoteNumBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					highestVoteNum_ = value;
					onChanged();
				} else {
					highestVoteNumBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000001;
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public Builder setHighestVoteNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder builderForValue) {
				if (highestVoteNumBuilder_ == null) {
					highestVoteNum_ = builderForValue.build();
					onChanged();
				} else {
					highestVoteNumBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000001;
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public Builder mergeHighestVoteNum(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id value) {
				if (highestVoteNumBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)
							&& highestVoteNum_ != cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance()) {
						highestVoteNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.newBuilder(highestVoteNum_).mergeFrom(value).buildPartial();
					} else {
						highestVoteNum_ = value;
					}
					onChanged();
				} else {
					highestVoteNumBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000001;
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public Builder clearHighestVoteNum() {
				if (highestVoteNumBuilder_ == null) {
					highestVoteNum_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.getDefaultInstance();
					onChanged();
				} else {
					highestVoteNumBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder getHighestVoteNumBuilder() {
				bitField0_ |= 0x00000001;
				onChanged();
				return getHighestVoteNumFieldBuilder().getBuilder();
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder getHighestVoteNumOrBuilder() {
				if (highestVoteNumBuilder_ != null) {
					return highestVoteNumBuilder_.getMessageOrBuilder();
				} else {
					return highestVoteNum_;
				}
			}

			/**
			 * <code>required .protocolbuffer.Id highestVoteNum = 1;</code>
			 */
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder> getHighestVoteNumFieldBuilder() {
				if (highestVoteNumBuilder_ == null) {
					highestVoteNumBuilder_ = new com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Id.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.IdOrBuilder>(
							highestVoteNum_, getParentForChildren(), isClean());
					highestVoteNum_ = null;
				}
				return highestVoteNumBuilder_;
			}

			// optional .protocolbuffer.Value v = 2;
			private cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value v_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder> vBuilder_;

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public boolean hasV() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value getV() {
				if (vBuilder_ == null) {
					return v_;
				} else {
					return vBuilder_.getMessage();
				}
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public Builder setV(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value value) {
				if (vBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					v_ = value;
					onChanged();
				} else {
					vBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public Builder setV(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder builderForValue) {
				if (vBuilder_ == null) {
					v_ = builderForValue.build();
					onChanged();
				} else {
					vBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public Builder mergeV(cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value value) {
				if (vBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002) && v_ != cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance()) {
						v_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.newBuilder(v_).mergeFrom(value).buildPartial();
					} else {
						v_ = value;
					}
					onChanged();
				} else {
					vBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000002;
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public Builder clearV() {
				if (vBuilder_ == null) {
					v_ = cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.getDefaultInstance();
					onChanged();
				} else {
					vBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder getVBuilder() {
				bitField0_ |= 0x00000002;
				onChanged();
				return getVFieldBuilder().getBuilder();
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			public cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder getVOrBuilder() {
				if (vBuilder_ != null) {
					return vBuilder_.getMessageOrBuilder();
				} else {
					return v_;
				}
			}

			/**
			 * <code>optional .protocolbuffer.Value v = 2;</code>
			 */
			private com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder> getVFieldBuilder() {
				if (vBuilder_ == null) {
					vBuilder_ = new com.google.protobuf.SingleFieldBuilder<cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value, cn.com.sparkle.paxos.stablestorage.model.StoreModel.Value.Builder, cn.com.sparkle.paxos.stablestorage.model.StoreModel.ValueOrBuilder>(
							v_, getParentForChildren(), isClean());
					v_ = null;
				}
				return vBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:protocolbuffer.SuccessfulRecord)
		}

		static {
			defaultInstance = new SuccessfulRecord(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:protocolbuffer.SuccessfulRecord)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_protocolbuffer_Value_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_protocolbuffer_Value_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_protocolbuffer_Id_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_protocolbuffer_Id_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_protocolbuffer_InstanceVoteRecord_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_protocolbuffer_InstanceVoteRecord_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_protocolbuffer_SuccessfulRecord_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_protocolbuffer_SuccessfulRecord_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\013store.proto\022\016protocolbuffer\"%\n\005Value\022\014"
						+ "\n\004type\030\001 \002(\005\022\016\n\006values\030\002 \003(\014\")\n\002Id\022\022\n\nin"
						+ "creaseId\030\001 \002(\003\022\017\n\007address\030\002 \002(\t\"\232\001\n\022Inst"
						+ "anceVoteRecord\022*\n\016highestJoinNum\030\002 \002(\0132\022" + ".protocolbuffer.Id\022+\n\017highestVotedNum\030\003 "
						+ "\001(\0132\022.protocolbuffer.Id\022+\n\014highestValue\030" + "\004 \001(\0132\025.protocolbuffer.Value\"`\n\020Successf"
						+ "ulRecord\022*\n\016highestVoteNum\030\001 \002(\0132\022.proto" + "colbuffer.Id\022 \n\001v\030\002 \001(\0132\025.protocolbuffer"
						+ ".ValueB6\n(cn.com.sparkle.paxos.stablesto", "rage.modelB\nStoreModel" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_protocolbuffer_Value_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_protocolbuffer_Value_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_protocolbuffer_Value_descriptor, new java.lang.String[] { "Type", "Values", });
				internal_static_protocolbuffer_Id_descriptor = getDescriptor().getMessageTypes().get(1);
				internal_static_protocolbuffer_Id_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_protocolbuffer_Id_descriptor, new java.lang.String[] { "IncreaseId", "Address", });
				internal_static_protocolbuffer_InstanceVoteRecord_descriptor = getDescriptor().getMessageTypes().get(2);
				internal_static_protocolbuffer_InstanceVoteRecord_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_protocolbuffer_InstanceVoteRecord_descriptor, new java.lang.String[] { "HighestJoinNum", "HighestVotedNum",
								"HighestValue", });
				internal_static_protocolbuffer_SuccessfulRecord_descriptor = getDescriptor().getMessageTypes().get(3);
				internal_static_protocolbuffer_SuccessfulRecord_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_protocolbuffer_SuccessfulRecord_descriptor, new java.lang.String[] { "HighestVoteNum", "V", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {},
				assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
